# Generated by Django 3.0.6 on 2020-05-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
